name: AnarchyChat
version: 1.1.0
main: earth2b2t.anarchychat.AnarchyChatPlugin
commands:
  ignore:
    usage: /ignore <name>
    description: Ignore a player
    permission: anarchychat.ignore
  ignorehard:
    usage: /ignorehard <name>
    permission: anarchychat.ignorehard
    description: Ignore a player permanently
  ignorelist:
    usage: /ignorelist
    description: Show ignored players
    permission: anarchychat.ignorelist
  tell:
    usage: /tell <name> <message...>
    description: Send message to a player
    permission: anarchychat.tell
    aliases: [ "message", "msg", "whisper", "w" ]
  reply:
    usage: /reply <message...>
    description: Reply to a player
    permission: anarchychat.reply
    aliases: [ "r" ]
  ignorelang:
    usage: /ignorelang <language>
    description: Change preferred language
    permission: anarchychat.ignorelang
  mute:
    usage: /mute <name>
    description: Mute a player
    permission: anarchychat.mute
    aliases: [ "mute", "gmute" ]
  pmute:
    usage: /pmute <name>
    description: Prevent a player from using private message
    permission: anarchychat.pmute
  mutelist:
    usage: /mutelist <name>
    description: Show muted players
    permission: anarchychat.mutelist
permissions:
  anarchychat.ignore:
    default: true
  anarchychat.ignorehard:
    default: true
  anarchychat.ignorelist:
    default: true
  anarchychat.tell:
    default: true
  anarchychat.reply:
    default: true
  anarchychat.ignorelang:
    default: true
  anarchychat.mute:
    default: op
  anarchychat.pmute:
    default: op
  anarchychat.mutelist:
    default: op
